"""Business logic services package."""

from app.services.agent_tools import (
    AccountBalance,
    AccountBalances,
    DATA_FETCHING_TOOLS,
    DOCUMENT_PROCESSING_TOOLS,
    ExtractedData,
    MatchedAccount,
    MatchedSupplier,
    ToolContext,
    Transaction,
    categorize_expense,
    extract_document_data,
    get_account_balances,
    get_chart_of_accounts,
    get_customers,
    get_data_fetching_tools,
    get_document_processing_tools,
    get_recent_transactions,
    get_suppliers,
    get_tool_context,
    identify_supplier,
    set_tool_context,
)
from app.services.auth import AuthenticationError, AuthService, TokenPair
from app.services.llm import (
    LLMConfig,
    LLMConnectionError,
    LLMError,
    LLMModelNotFoundError,
    LLMProvider,
    LLMProviderError,
    LLMService,
    LLMTimeoutError,
    Message,
    ModelInfo,
)
from app.services.ocr import (
    OCRConnectionError,
    OCRError,
    OCRModelNotFoundError,
    OCRProcessingError,
    OCRResult,
    OCRService,
)

__all__ = [
    # Agent Tools
    "ToolContext",
    "set_tool_context",
    "get_tool_context",
    "get_chart_of_accounts",
    "get_suppliers",
    "get_customers",
    "get_recent_transactions",
    "get_account_balances",
    "get_data_fetching_tools",
    "DATA_FETCHING_TOOLS",
    "Transaction",
    "AccountBalance",
    "AccountBalances",
    # Document Processing Tools
    "extract_document_data",
    "categorize_expense",
    "identify_supplier",
    "get_document_processing_tools",
    "DOCUMENT_PROCESSING_TOOLS",
    "ExtractedData",
    "MatchedAccount",
    "MatchedSupplier",
    # Auth
    "AuthService",
    "AuthenticationError",
    "TokenPair",
    # LLM
    "LLMService",
    "LLMConfig",
    "LLMProvider",
    "LLMError",
    "LLMConnectionError",
    "LLMModelNotFoundError",
    "LLMProviderError",
    "LLMTimeoutError",
    "Message",
    "ModelInfo",
    # OCR
    "OCRService",
    "OCRResult",
    "OCRError",
    "OCRConnectionError",
    "OCRProcessingError",
    "OCRModelNotFoundError",
]
